[package]
name = "mpu6050-async"
version = "0.1.0"
authors = ["Max Daubmann"]
edition = "2024"

description = "Platform agnostic async driver for MPU6050 6-axis IMU"
repository = "TODO"
readme = "README.md"
keywords = ["mpu6050", "imu", "embedded"]
license = "MIT"

[dependencies]
embedded-hal-async = "^1.0.0"
libm = "0.2.1"

[dependencies.nalgebra]
default-features = false
version = "0.32.3"

[dev-dependencies]
i2cdev = "0.6.0"
linux-embedded-hal = "0.4.0"
